# Generated by Django 2.2.14 on 2020-08-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200807_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('F', 'Fruits'), ('V', 'Vegetables'), ('D', 'Dairy'), ('M', 'Meat'), ('B', 'Beverages')], max_length=2),
        ),
    ]
